- name: GRAB F5 FACTS
  hosts: f5
  connection: local
  gather_facts: no

  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
          - all
        provider:
          server: "{{ private_ip }}"
          user: "{{ ansible_user }}" 
          password: "{{ ansible_ssh_pass }}"
          validate_certs: no
      register: device_facts
      delegate_to: localhost

    - name: DISPLAY BIG-IP SYSTEM INFOMATION
      debug:
        var: device_facts